FROM electronuserland/builder:latest

WORKDIR /project
COPY . .
RUN corepack enable \
  && corepack prepare pnpm@10.15.0 --activate \
  && pnpm install --frozen-lockfile

CMD ["pnpm", "package:linux"]
